[build-system]
requires = ["setuptools>=42", "wheel", "pybind11", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "MMVII"
dynamic = ["version", "authors", "requires-python", "description"]
dependencies = [
  "numpy"
]

